name: 03 MLProject CI Without Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "3_Workflow_CI/**"
      - ".github/workflows/03-mlproject-ci.yml"

jobs:
  mlproject-training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 3_Workflow_CI/MLProject/requirements.txt

      - name: Run MLflow Project
        run: |
          cd 3_Workflow_CI/MLProject
          mlflow run . --env-manager=local

      - name: Show MLflow runs
        run: |
          cd 3_Workflow_CI/MLProject
          ls -R mlruns || true

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: 3_Workflow_CI/MLProject/mlruns