name: MLflow Project CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Directory Structure
        run: |
          pwd
          echo "=== ROOT ==="
          ls -la
          echo "=== 3_Workflow_CI ==="
          ls -la 3_Workflow_CI || true
          echo "=== MLProject ==="
          ls -la 3_Workflow_CI/MLProject || true
          echo "=== Dataset Folder ==="
          ls -la 3_Workflow_CI/MLProject/titanic_preprocessing || true
          echo "=== Find CSV Files ==="
          find . -name "*.csv"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 3_Workflow_CI/MLProject/requirements.txt

      - name: Check dataset files
        run: |
          test -f 3_Workflow_CI/MLProject/titanic_preprocessing/train.csv
          test -f 3_Workflow_CI/MLProject/titanic_preprocessing/test.csv
          echo "Dataset files found."

      - name: Run MLflow Project
        run: |
          cd 3_Workflow_CI/MLProject
          mlflow run . --env-manager=local

      - name: Show MLflow Output
        run: |
          cd 3_Workflow_CI/MLProject
          ls -R mlruns || true

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: 3_Workflow_CI/MLProject/mlruns